### ISSUE TITLE
[Feature] lazy loaded modules & storage persistence

### ISSUE THREAD

**Issue by murraybauer** [HarmoWatch/ngx-redux-core#38]
Love the concept, but it needs to work with lazy loaded modules & have an OTB storage persistence option (that works with lazy loaded modules).  Any plans?

**Comment by kay-schecker** [comment]
Hi @murraybauer, great to hear, that you love the concept. Lazy loaded modules are already supported. Please see https://github.com/HarmoWatch/ngx-redux-core/blob/master/docs/how-to/use-lazy-loading.md 

Regarding the storage option:

Right now you‘ve the possibility to load the state, from your storage, within your state provider’s [getInitialState](https://github.com/HarmoWatch/ngx-redux-core/blob/master/docs/api/redux-state-provider.md) method. What i can imagine, is a new configuration option at the ReduxModule.forRoot config, where you can provide a persistance adapter. I can provide this adapter as the first argument to the getInitialState method then.

`
getInitialState(persistence: ReduxPersistenceAdapter): SomeState {
    return persistence.getState<SomeState>(this.name); // (this.name is the decorated name)
}
`

I hope this was helpful

**Comment by murraybauer** [comment]
@kay-schecker Thanks for your quick response.

Awesome - I must have missed the lazy load docs!

Plugable persistence adaptor support would be great.  It was great to see the `getInitialState()` method already supports async resolution (via promise/observable) for this.

Is it possible to support something like [redux-persist](https://github.com/rt2zz/redux-persist/blob/master/README.md)? I've used it several times with the `localForage` storage engine.  It has no other dependencies, is very small (kb wise) and well-maintained.  It provides a number basic features like custom transforms, black/white lists, schema migration support etc that you need.

The reason for my question re both persistence and lazy loaded modules/reducers, has been that in the past redux persistence adaptors have always stored the entire state tree in a single object, and re-hydrate the entire tree on app load which meant it didn't work with lazy loaded reducers added later.  It seems `redux-persist` has not solved this with [nested persists](https://github.com/rt2zz/redux-persist/blob/master/README.md#nested-persists)

**Comment by kay-schecker** [comment]
Hi @murraybauer,

I've added a new manual how you can [create your own redux store](https://github.com/HarmoWatch/ngx-redux-core/blob/master/docs/how-to/provide-your-own-store.md). Trough this feature it's possible to integrate [redux-persist](https://github.com/rt2zz/redux-persist/blob/master/README.md). You can access the state which was initialized before the `getInitialState` method was called, like this:

```ts
getInitialState(): Promise<TodoState> {
  return this.getState().then(initialState => {
    return Promise.resolve({
      ...initialState,
      items: initialState.items || [],
    });
  });
}
```

Cheers
Kay

**Comment by kay-schecker** [comment]
To use this *new feature* you've to install the **next** version (0.2.3-0).

```
$ npm install @harmowatch/ngx-redux-core@next
```
