### ISSUE TITLE
Interface naming suggestions

### ISSUE THREAD

**Issue by dummdidumm** [HarmoWatch/ngx-redux-core#45]
First of all, great take on redux with angular!

I have some naming suggestions from browsing the repo:

- interface ReduxModuleChildConfig is located inside file redux-child-module-config.interface.ts . "child" and "module" are switched. This is a little confusing. I don't know which variant you want but I suggest to name the file the same as the interface.
- same for interface ReduxModuleRootConfig / redux-root-module-config.interface.ts
- ReduxActionWithPayload is inside file redux-action.interface.ts -> same issue as the other two. In this case I suggest to name the interface ReduxAction, it's more concise.

**Comment by kay-schecker** [comment]
Hi @dummdidumm 

Thank you very much for your feedback!
I've just fixed the naming issues.
